on: 
  pull_request:
    branches:
    - master
  push:
    branches:
    - master
  workflow_call:

    
# comments
name: ASP.NET Core

jobs:

  build:
    name: Build
    
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        
    runs-on: ${{ matrix.os }}
    steps:
    - run: ext 1
      if: matrix.os == 'macos-latest'
      
    - run: echo $runner_payload
      id: dump-runner
      env:
        runner_payload: ${{ toJson(runner) }}
      
    - run: echo $github_payload
      id: dump-github
      env: 
        github_payload: ${{ toJson(github) }}
    
    - run: echo $job_payload
      id: dump-job
      env:
        job_payload: ${{ toJson(job) }}
    
    - run: echo $steps_payload
      id: dump-steps
      env:
        steps_payload: ${{ toJson(steps) }}
        
    - run: echo $strategy_payload
      id: dump-strategy
      env:
        strategy_payload: ${{ toJson(strategy) }}
        

