on: [push, pull_request]

name: ASP.NET Core

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    actions:
    
    - uses: actions/checkout@master
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@master
      with:
        version: 2.2.300

    - name: Build with dotnet
      run: dotnet build --configuration Release
      
    - run: echo $github_payload
      env: 
        github_payload: ${{ toJson(github) }}
    
    - run: echo $job_payload
      env:
        job_payload: ${{ toJson(job) }}
    
    - run: echo $steps_payload
      env:
        steps_payload: ${{ toJson(steps) }}
    
    - run: echo $runner_payload
      env:
        runner_payload: ${{ toJson(runner) }}
        
    - run: |
        if [ ${{ github.event.pull_request.head.repo.full_name }} == ${{ github.event.pull_request.base.repo.full_name }} ];
        then
          echo "Hello base repo"
        else
          echo "Hello fork repo"
        fi
        
    - name: 'Check that the cache files are consistent with their remote sources'
      run: |
        if [[ $(git diff --name-only "$(git merge-base origin/"$TARGET_BRANCH" HEAD)" HEAD -- .yarn/{cache,virtual} | wc -l) -gt 0 ]]; then
          rm -rf ./.yarn/cache
          node ./scripts/run-yarn.js
        fi
      if: github.event.pull_request != ''
      env:
        TARGET_BRANCH: ${{ github.event.pull_request.base.ref }}
