on: [push, pull_request, release]

name: ASP.NET Core

jobs:

  build:
    name: Build

    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v1
    
    - name: Setup .NET Core
      id: setup-dotnet
      uses: actions/setup-dotnet@v1
      with:
        version: 2.2.300

    - name: Build with dotnet
      id: build-dotnet
      run: dotnet build --configuration Release

    - run: echo $runner_payload
      id: dump-runner
      env:
        runner_payload: ${{ toJson(runner) }}
      
    - run: echo $github_payload
      id: dump-github
      env: 
        github_payload: ${{ toJson(github) }}
    
    - run: echo $job_payload
      id: dump-job
      env:
        job_payload: ${{ toJson(job) }}
    
    - run: echo $steps_payload
      id: dump-steps
      env:
        steps_payload: ${{ toJson(steps) }}
