on: [push]

name: ASP.NET Core

jobs:

  build:
    name: Build
    runs-on: ${{ matrix.vm }}
    strategy:
      matrix:
        vm: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        
    actions:
    
    - uses: actions/checkout@master
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@master
      with:
        version: 2.2.300

    - name: Build with dotnet
      run: dotnet build --configuration Release
        
    - run: |
        if [ '${{ github.event.pull_request.head.ref }}' == '${{ github.event.pull_request.base.ref }}' ];
          echo "Hello base repo"
        else
          echo "Hello fork repo"
        fi
      if: github.event.pull_request != ''
