on: [push]

name: ASP.NET Core

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    actions:
    
    - uses: uses: actions/checkout@master
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@master
      with:
        version: 2.2.300

    - name: Build with dotnet
      run: dotnet build --configuration Release
      
    - run: echo $github_payload
      env: 
        github_payload: ${{ toJson(github) }}
    
    - run: echo $job_payload
      env:
        job_payload: ${{ toJson(job) }}
    
    - run: echo $steps_payload
      env:
        steps_payload: ${{ toJson(steps) }}
    
    - run: echo $runner_payload
      env:
        runner_payload: ${{ toJson(runner) }}
